#ifndef SNGCONNECTIONMANAGER_GLOBAL_H
#define SNGCONNECTIONMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SNGCONNECTIONMANAGER_LIBRARY)
#  define SNGCONNECTIONMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SNGCONNECTIONMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SNGCONNECTIONMANAGER_GLOBAL_H
